/*
 * Amritpal Singh 
 * Write a java program implementing the towers of Hanoi code shown in class to handle 10 disks and give the output of using it. 
 * Recursively calculates movements required to successfully move 10 plates onto one stack in order, using only 3 possible stacks.
 */
public class TowersOfHanoi {

	public static void moveDisks(int n, char fromTower, char toTower, char auxTower) {
		
		if (n==1) {
		System.out.println("Move disk " + n + " from Tower " + fromTower + " to tower " + toTower);	
	}
		else {
			moveDisks (n -1, fromTower, auxTower, toTower);
			System.out.println("Move disk " + n + " from Tower " + fromTower + " to tower " + toTower);
			moveDisks(n-1, auxTower, toTower, fromTower);
		}
	}
	
	public static void main (String [] args) {
		moveDisks(10, 'A', 'B', 'C');
	}
}

/*Sample Output:
It's really long :P

Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 6 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 7 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 5 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 6 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 8 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 6 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 5 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 7 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 6 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 9 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 5 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 6 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 7 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 6 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 5 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 8 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 6 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 7 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 5 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 6 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 10 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 6 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 5 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 7 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 6 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 8 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 5 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 6 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 7 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 6 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 5 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 9 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 6 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 7 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 5 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 6 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 8 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 6 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 5 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 7 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 5 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 4 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 6 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 4 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 3 from Tower B to tower A
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 5 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 3 from Tower A to tower C
Move disk 1 from Tower B to tower A
Move disk 2 from Tower B to tower C
Move disk 1 from Tower A to tower C
Move disk 4 from Tower A to tower B
Move disk 1 from Tower C to tower B
Move disk 2 from Tower C to tower A
Move disk 1 from Tower B to tower A
Move disk 3 from Tower C to tower B
Move disk 1 from Tower A to tower C
Move disk 2 from Tower A to tower B
Move disk 1 from Tower C to tower B
*/
